- name: Restart Service
  hosts: "{{ host }}"
  become: yes  # Enable privilege escalation (sudo)
  vars:
    service_name: "apache2"  # Change this to your service name

  tasks:
    - block:
        - name: Stop the Service
          service:
            name: "{{ service_name }}"
            state: stopped
          register: stop_result

        - name: Start the Service
          service:
            name: "{{ service_name }}"
            state: started

        - name: Check Service Status
          systemd:
            name: "{{ service_name }}"
          register: apache_status

        - name: Display Service Status
          debug:
            var:  apache_status

        - name: Display Success Message
          debug:
            msg: "OUTPUT: SUCCESS: Service started"
      rescue:
        - name: Display Error Message
          debug:
            #msg: "Failed to restart the service: {{ stop_result.msg }}"
            msg: "OUTPUT: FAILED: Task {{ ansible_failed_task.name }} Failed and the ERROR: {{ ansible_failed_result }}"

