---
- name: Call Template in Ansible Automation Platform
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Fetch the TEMPLATE by id
      community.general.one_template:
        template: 132
        name: rayank-readCSV
      register: result

    - name: Print the TEMPLATE properties
      ansible.builtin.debug:
        var: result
