---
- name: Launch Ansible Job

  hosts: localhost

  gather_facts: no

  tasks:

    - name: Launch AAP Job Template

      awx.job_template:

        tower_host: 35.154.24.128

        username: rinki

        password: rinki

        validate_certs: False  # Set to True if you want to validate SSL certificates

        job_template: 132
