--- 
- name: playbook to get hostname
  hosts: "{{ host }}"
  gather_facts: no

  tasks:
    - block:
        - name: "Show hostname"
          command: hostname
          register: details
        - name: 'Get Interfaces details'
          debug:
            msg: "OUTPUT: {{ details.stdout }}"
            
      rescue: 
        - name: Log Output For Failure
          debug:
            msg: "OUTPUT : FAILED : Task {{ ansible_failed_task.name }} Failed and the ERROR: {{ ansible_failed_result }}"
          failed_when: True
