--- 
- name: playbook to get hostname
  hosts: "{{ host }}"
  gather_facts: no

  tasks:
    - block:
        - name: "Show hostname server"
          command: hostname
          register: details
          failed_when: true
        - name: 'Get Interfaces details'
          debug:
            msg: "OUTPUT: {{ details.stdout }}"
            
      rescue: 
        - name: Log Output For Failure
          debug:
            msg: "OUTPUT : FAILED : Task {{ ansible_failed_task.name }} Failed and the ERROR: {{ ansible_failed_result.msg }}"
          failed_when: True
