--- 
- name: playbook to get hostname
  hosts: "{{ host }}"
  gather_facts: yes

  tasks:
    - name: "Show hostname"
      command: hostname
      register: details
    - name: 'Get Interfaces details'
      debug:
        msg: "OUTPUT: {{ details.stdout }}"
