---
- name: playbook to execute script
  hosts: "{{ HOSTS }}"
  gather_facts: yes
  vars:
    host: '{{ lookup("env", "VMWARE_HOST") }}'
    username: '{{ lookup("env", "VMWARE_USER") }}'
    password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
    script_path: "{{ script_path }}"
    usecaseName: "{{ usecaseName }}"
  
  tasks:
    - block:
        - name: Check if the file exists
          win_stat:
            path: "{{ script_path }}"
          register: File_output
          
        - name: Print File location
          debug:
            msg: "File exists at the specified location: {{ File_output }}"
          when: File_output.stat.exists
             
        - name: Execute Powershell Script present in the jump host
          win_command: powershell.exe -ExecutionPolicy ByPass -File "{{ script_path }}"  -username "{{ username }}" -password "{{ password }}" -usecaseName "{{ usecaseName }}"
          register: result
          changed_when: false

        - name: Print the powershell script Output
          debug:
            msg: "OUTPUT: SCRIPT RESULT : {{ result.stdout_lines }}"
          
        - name: Script Execution sucessfull.
          debug:
            msg: Script executed successfully
          when: result is succeeded
          
      rescue:
        - name: Log Output For Failure
          debug:
            msg: "Failed: {{ ansible_failed_task.name }} Failed and the ERROR: {{ ansible_failed_result }}"
